name: Build (PR, reusable)

on:
  workflow_call:
    inputs:
      package-path:
        required: true
        type: string

jobs:
  build-dotnet:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Build and Test .NET solution
        uses: ./.github/actions/build-dotnet
        with:
          working-directory: ${{ inputs.package-path }}