name: Build all templates (reusable)

on:
  workflow_call:

jobs:
  build-common:
    name: Build common package
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      - name: Build and Test .NET solution
        uses: Arbeidstilsynet/action-dotnet-build@46ba407f9370390d5b20f3d01f4bd9a191c78345 # v1
        with:
          working-directory: "./templates/common-package/SamplePackage"

  build-hexarch:
    name: Build hexarch package
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      - name: Build and Test .NET solution
        uses: Arbeidstilsynet/action-dotnet-build@46ba407f9370390d5b20f3d01f4bd9a191c78345 # v1
        with:
          working-directory: "./templates/hexarch"
