name: Build all templates (reusable)

on:
  workflow_call:

jobs:
  build-common:
    name: Build common package
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: Build and Test .NET solution
        uses: Arbeidstilsynet/action-dotnet-build@de0c8a04f5db83cd01c03bf8b7056e00b6e014d3 # v4
        with:
          working-directory: "./templates/common-package/SamplePackage"

  build-hexarch:
    name: Build hexarch package
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: Build and Test .NET solution
        uses: Arbeidstilsynet/action-dotnet-build@de0c8a04f5db83cd01c03bf8b7056e00b6e014d3 # v4
        with:
          working-directory: "./templates/hexarch"
