name: Build and Publish Packages

on:
  pull_request:
  push:
    branches: [main]

jobs:
  build-common:
    name: Build common package
    uses: ./.github/workflows/build-pr-template.yaml
    with:
      package-path: "./templates/common-package/SamplePackage"
  
  build-extension:
    name: Build extension package
    uses: ./.github/workflows/build-pr-template.yaml
    with:
      package-path: "./templates/extension-package/SampleExtension"

  build-hexarch:
    name: Build hexarch package
    uses: ./.github/workflows/build-pr-template.yaml
    with:
      package-path: "./templates/hexarch"

  post-build-checks:
    name: Post Build Checks
    needs: [build-common, build-extension, build-hexarch]
    if: github.ref != 'refs/heads/main'
    uses: ./.github/workflows/post-build-pr-template.yml
    secrets: inherit
    with:
      package-path: "./"

  publish:
    name: Publish Packages
    needs: [build-common, build-extension, build-hexarch]
    if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/publish-template.yml
    secrets: inherit
    with:
      package-path: "./"
