name: Build and Publish Packages

on:
  push:
    branches: [main]

jobs:
  build:
    name: Build all templates
    uses: ./.github/workflows/build-template.yaml

  publish:
    name: Publish Packages
    needs: build
    uses: ./.github/workflows/publish-template.yml
    secrets: inherit
    permissions:
      contents: write
      id-token: write
    with:
      package-path: "./"
