name: Post Build (PR, reusable)

on:
  workflow_call:
    inputs:
      package-path:
        required: true
        type: string

jobs:
  post-build-checks:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
        with:
          fetch-depth: 0

      - name: Get version and name from csproj file
        id: get_metadata_from_csprojectfile
        uses: Arbeidstilsynet/action-dotnet-get-csproj-metadata@1ce26ff56a71e150145f2f95c235a0d18c899bb7 # v1
        with:
          working-directory: ${{ inputs.package-path }}
      - name: Check if package version exists
        id: nuget_version_check
        uses: Arbeidstilsynet/action-nuget-check-published@496c4c1c088db11ed169b3ace6cffd5dd9a681fa # v2
        with:
          name: ${{ steps.get_metadata_from_csprojectfile.outputs.name }}
          version: ${{ steps.get_metadata_from_csprojectfile.outputs.version }}
          source-feed: "AT.Public.NuGet"
      - name: Check if version is prerelease
        id: prerelease_check
        run: |
          if [ "${{ steps.nuget_version_check.outputs.published }}" = "true" ]; then
            echo "❌ This pre release version is already published. Either increase the pre-release version or switch to a release version if the branch is ready."
            exit 1
          fi
          VERSION="${{ steps.get_metadata_from_csprojectfile.outputs.version }}"
          # Check if the version string contains a prerelease identifier (e.g., alpha, beta, rc)
          if [[ "$VERSION" == *-* ]]; then
            echo "is_prerelease=true" >> $GITHUB_OUTPUT
          else
            echo "is_prerelease=false" >> $GITHUB_OUTPUT
          fi
      - name: Publish prerelease package
        if: steps.prerelease_check.outputs.is_prerelease == 'true'
        uses: Arbeidstilsynet/action-dotnet-publish@1f0a759b152f5e6024fec0025db31ff4f5a0192d # v2
        with:
          working-directory: ${{ inputs.package-path }}
          nuget-auth-token: ${{ secrets.AZURE_DEVOPS_PUBLISH_PACKAGE_PAT }}
      - name: Fail if prerelease was published
        if: steps.prerelease_check.outputs.is_prerelease == 'true'
        run: |
          echo "✅ Prerelease package was published successfully."
          echo "❌ This branch cannot be merged until the prerelease version is removed from the .csproj file."
          exit 1
      - name: Check if package version was updated
        id: get_version
        run: |
          VERSION="${{ steps.get_metadata_from_csprojectfile.outputs.version }}"
          FOUND="${{ steps.nuget_version_check.outputs.last_version }}"
          if [ "${{steps.nuget_version_check.outputs.published }}" = "true" ]; then
            echo "❌ You did not increase the version number. This version ($VERSION) is the same as the last published version."
            exit 1
          else
            echo "✅ You increased the version number. The last published version was '$FOUND'. The new version $VERSION is going to be published when merging into main."
          fi

      - name: Check for changelog
        run: |
          CHANGELOG=$(find "${{ inputs.package-path }}" -maxdepth 1 -name 'CHANGELOG.md' | head -n 1)
          if [ -f "$CHANGELOG" ]; then
            echo "Changelog found."
            # Optionally, check if the changelog contains the version string
            if grep -q "${{ steps.get_metadata_from_csprojectfile.outputs.version }}" "$CHANGELOG"; then
              echo "✅ Changelog contains entry for version ${{ steps.get_metadata_from_csprojectfile.outputs.version }}."
            else
              echo "❌ Changelog does not contain entry for version ${{ steps.get_metadata_from_csprojectfile.outputs.version }}."
              exit 1
            fi
          else
            echo "❌ No changelog found. Please add a CHANGELOG.md file to the package path ${{ inputs.package-path }}."
            exit 1
          fi
