name: Build packages and run post-build checks

on:
  pull_request:

permissions:
  contents: read
  packages: write

jobs:
  pre-build-checks:
    name: Check if build is needed
    uses: ./.github/workflows/pre-build-pr-template.yaml

  build:
    name: Build all templates
    needs: pre-build-checks
    if: ${{ needs.pre-build-checks.outputs.should-continue == 'true' }}
    uses: ./.github/workflows/build-template.yaml

  post-build-checks:
    name: Post Build Checks
    needs: build
    uses: ./.github/workflows/post-build-pr-template.yaml
    secrets: inherit
    with:
      package-path: "./"
