name: Pre-Build Check (reusable)

on:
  workflow_call:
    outputs:
      should-continue:
        description: "Indicates whether the workflow should continue based on changes in the templates directory."
        value: ${{ jobs.check.outputs.should-continue }}

jobs:
  check:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    outputs:
      should-continue: ${{ steps.check_changes_for_publishing.outputs.changes_detected }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 0

      - name: Changes for publishing?
        uses: Arbeidstilsynet/action-check-changes@6e51077b178b819e4194f40e32bd562df0954f3f # v1
        id: check_changes_for_publishing
        with:
          base-ref: origin/main
          include: |
            templates/common-package
            templates/hexarch
          exclude: |
            templates/hexarch/compose.yaml
            templates/hexarch/compose.infra.yaml
            templates/hexarch/package.json
