name: Pre-Build Check (reusable)

on:
  workflow_call:
    outputs:
      should-continue:
        description: "Indicates whether the workflow should continue based on changes in the templates directory."
        value: ${{ jobs.check.outputs.should-continue }}

jobs:
  check:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    outputs:
      should-continue: ${{ steps.check_changes.outputs.should-continue }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
        with:
          fetch-depth: 0
      - name: Check if changes are inside template path
        id: check_changes
        run: |
          changed_files=$(git --no-pager diff --name-only origin/main...HEAD | grep "templates/" || true)
          # If empty, do not continue
            if [ -z "$changed_files" ]; then
            echo "should-continue=false" >> $GITHUB_OUTPUT
            echo "No changes detected which require a version update. Exiting workflow gracefully."
            exit 0
          fi
          # Check if all changed files are markdown files
            non_dotnet_related_files=$(echo "$changed_files" | grep -vE '\.md$|Dockerfile|compose.*\.ya?ml$' || true)
          # If empty, do not continue
          if [ -z "$non_dotnet_related_files" ]; then
            echo "should-continue=false" >> $GITHUB_OUTPUT
            echo "No changes detected which require a version update. Exiting workflow gracefully."
          else
            echo "should-continue=true" >> $GITHUB_OUTPUT
            echo "Changes detected which require a version update. The workflow will continue..."
          fi
          exit 0
