networks:
  HexagonalArchitectureTemplateDocker_network:
    name: HexagonalArchitectureTemplateDocker_network
    external: false

services:
  postgres_db:
    image: postgres:17-alpine@sha256:b8bf2b22777752274351a161f5c99d55728a2652a87ea655e02cfa20cb44f825
    networks:
      - HexagonalArchitectureTemplateDocker_network
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=demo_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 1s
      timeout: 5s
      retries: 10

  unleash_web:
    image: unleashorg/unleash-server@sha256:f648f0be6c7972c244b1172f72400c54c593a4957230d2673ca134ad7d873e77
    networks:
      - HexagonalArchitectureTemplateDocker_network
    ports:
      - "4242:4242"
    environment:
      # This points Unleash to its backing database
      DATABASE_URL: "postgres://postgres:postgres@postgres_db:5432/demo_db"
      # Disable SSL for database connections.
      DATABASE_SSL: "false"
      # Changing log levels:
      LOG_LEVEL: "warn"
      INIT_FRONTEND_API_TOKENS: "default:development.unleash-insecure-frontend-api-token"
      # The default API token is insecure and should not be used in production.
      INIT_BACKEND_API_TOKENS: "default:development.unleash-insecure-api-token"
    depends_on:
      postgres_db:
        condition: service_healthy
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:4242/health || exit 1
      interval: 1s
      timeout: 1m
      retries: 5
      start_period: 15s

  monitoring_otel:
    container_name: monitoring_otel
    image: grafana/otel-lgtm@sha256:557ddac3121c7b470b59dfb4f69a4d24d9f6a3c9d63b330152498a3650f720bf
    networks:
      - HexagonalArchitectureTemplateDocker_network
    restart: always
    profiles:
      - monitoring
    ports:
      - "4317:4317" # OTLP gRPC receiver
      - "4318:4318" # OTLP HTTP receiver
      - "4000:3000" # Grafana UI

volumes:
  postgres-data:
