networks:
  applocal_network:
    external: false

services:
  postgres:
    image: postgres:17-alpine@sha256:f325a29ec9deb7039c5f07761d77d79d537dac836ecd99f982f6ca5476724604
    networks:
      - applocal_network
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=demo_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 1s
      timeout: 5s
      retries: 10

  monitoring_otel_collector:
    container_name: monitoring_otel_collector
    image: otel/opentelemetry-collector-contrib:0.98.0@sha256:5cea85bcbc734a3c0a641368e5a4ea9d31b472997e9f2feca57eeb4a147fcf1a
    networks:
      - applocal_network
    restart: always
    command:
      - --config=/etc/otel-collector.yaml
    volumes:
      - ./.docker-compose.config/otel-collector.yaml:/etc/otel-collector.yaml
    ports:
      - "4317:4317"   # OTLP gRPC receiver
    profiles: ["monitoring"]
    depends_on:
      - monitoring_mimir
      - monitoring_tempo
      - monitoring_loki

  monitoring_tempo:
    container_name: monitoring_tempo
    image: grafana/tempo:2.4.1@sha256:5b9c08f6d8fb43b3b72dfd1252ba4f198b11a245257bf76ee2ca13e243bac565
    networks:
      - applocal_network
    restart: always
    command:
      - -config.file=/etc/tempo.yaml
      - -log.level=error
    volumes:
      - ./.docker-compose.config/tempo.yaml:/etc/tempo.yaml
    profiles: ["monitoring"]

  monitoring_mimir:
    container_name: monitoring_mimir
    image: grafana/mimir:2.12.0@sha256:2a0192459f5cf0c4f10b543e8d61f973d2e49921745196a09f83b6e4d428d9f8
    networks:
      - applocal_network
    restart: always
    command:
      - -config.file=/etc/mimir.yaml
      - -target=all
      - -log.level=error
    volumes:
      - ./.docker-compose.config/mimir.yaml:/etc/mimir.yaml
    profiles: ["monitoring"]

  monitoring_loki:
    container_name: monitoring_loki
    image: grafana/loki:3.0.0@sha256:757b5fadf816a1396f1fea598152947421fa49cb8b2db1ddd2a6e30fae003253
    networks:
      - applocal_network
    restart: always
    command:
      - -config.file=/etc/loki.yaml
      - -target=all
      - -log.level=error
    volumes:
      - ./.docker-compose.config/loki.yaml:/etc/loki.yaml
    profiles: ["monitoring"]

  monitoring_grafana:
    container_name: monitoring_grafana
    image: grafana/grafana:10.4.18@sha256:5f06f19d2a20c27a442b9bc1d57ec6730cb7be11d721f889369e823a2741ba1f
    networks:
      - applocal_network
    restart: always
    ports:
     - '3000:3000'
    volumes:
      - ./.docker-compose.config/grafana-datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
      - ./.docker-compose.config/grafana-dashboards.yaml:/etc/grafana/provisioning/dashboards/dashboards.yaml
      - ./.docker-compose.config/grafana-dashboards:/var/lib/grafana/dashboards
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_FEATURE_TOGGLES_ENABLE="traceqlEditor traceToMetrics metricsSummary"
      - GF_LOG_LEVEL=error
    extra_hosts:
      - "host.docker.internal:host-gateway"
    profiles: ["monitoring"]
    depends_on:
      - monitoring_otel_collector
      - monitoring_mimir
      - monitoring_tempo
      - monitoring_loki

volumes:
  postgres-data:
