networks:
  HexagonalArchitectureTemplateDocker_network:
    name: HexagonalArchitectureTemplateDocker_network
    external: false

services:
  postgres_db:
    image: postgres:17-alpine@sha256:f45469e6c408078412e20ac759530a28b752e201323f32b0bf04ec0f981037a5
    networks:
      - HexagonalArchitectureTemplateDocker_network
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=demo_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 1s
      timeout: 5s
      retries: 10

  unleash_web:
    image: unleashorg/unleash-server@sha256:92011963eeb67ded309319700298bbace59aa301ee31ffa0cd8ac9851561b745
    networks:
      - HexagonalArchitectureTemplateDocker_network
    ports:
      - "4242:4242"
    environment:
      # This points Unleash to its backing database
      DATABASE_URL: "postgres://postgres:postgres@postgres_db:5432/demo_db"
      # Disable SSL for database connections.
      DATABASE_SSL: "false"
      # Changing log levels:
      LOG_LEVEL: "warn"
      INIT_FRONTEND_API_TOKENS: "default:development.unleash-insecure-frontend-api-token"
      # The default API token is insecure and should not be used in production.
      INIT_BACKEND_API_TOKENS: "default:development.unleash-insecure-api-token"
    depends_on:
      postgres_db:
        condition: service_healthy
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:4242/health || exit 1
      interval: 1s
      timeout: 1m
      retries: 5
      start_period: 15s

  monitoring_otel:
    container_name: monitoring_otel
    image: grafana/otel-lgtm@sha256:d2f556b1033095d42fd6b5091ed9a091fd58793767f672b3086a4c98a9beb2d1
    networks:
      - HexagonalArchitectureTemplateDocker_network
    restart: always
    profiles:
      - monitoring
    ports:
      - "4317:4317" # OTLP gRPC receiver
      - "4318:4318" # OTLP HTTP receiver
      - "4000:3000" # Grafana UI

volumes:
  postgres-data:
