networks:
  applocal_network:
    external: false

services:
  monitoring_otel:
    container_name: monitoring_otel
    image: grafana/otel-lgtm
    networks:
      - applocal_network
    restart: always
    ports:
      - "4317:4317" # OTLP gRPC receiver
      - "4318:4318" # OTLP HTTP receiver
      - "4000:3000" # Grafana UI
