include:
  - compose.db.yaml
  - compose.monitoring.yaml

networks:
  applocal_network:
    external: false

services:
  api:
    build:
      context: .
    ports:
      - "8080:8080"
    networks:
      - applocal_network
    environment:
      Infrastructure__ConnectionString: Host=postgres;Port=5432;Database=demo_db;Username=postgres;Password=postgres
      Domain__SomeSetting: SomeValue
      API__Cors__AllowedOrigins__0: https://localhost:3000
      API__Cors__AllowCredentials: false
      OTEL_EXPORTER_OTLP_ENDPOINT: http://monitoring_otel:4317
    depends_on:
      postgres:
        condition: service_healthy
