include:
  - compose.infra.yaml

networks:
  HexagonalArchitectureTemplateDocker_network:
    name: HexagonalArchitectureTemplateDocker_network
    external: false

services:
  api:
    build:
      context: .
    ports:
      - "8080:8080"
    networks:
      - HexagonalArchitectureTemplateDocker_network
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_HTTP_PORT: "8080"
      Infrastructure__ConnectionString: Host=postgres_db;Port=5432;Database=demo_db;Username=postgres;Password=postgres
      API__Authentication__DangerousDisableAuth: "true"
      API__FeatureFlag__Url: http://unleash_web:4242/api/
      API__FeatureFlag__ApiKey: default:development.unleash-insecure-api-token
      API__FeatureFlag__AppName: HexagonalArchitectureTemplateDocker
      API__FeatureFlag__Environment: development
      OTEL_EXPORTER_OTLP_ENDPOINT: http://monitoring_otel:4317
    depends_on:
      postgres_db:
        condition: service_healthy
