networks:
  HexagonalArchitectureTemplateDocker_network:
    name: HexagonalArchitectureTemplateDocker_network
    external: false

services:
  postgres_db:
    image: postgres:17-alpine@sha256:9a78577340f3d26384b6aebeb475c0d46d664fd4ffa68503b4be4e4462745f94
    networks:
      - HexagonalArchitectureTemplateDocker_network
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=demo_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 1s
      timeout: 5s
      retries: 10

  unleash_web:
    image: unleashorg/unleash-server@sha256:fce12443d531064cca38d996a9913179e3e36955d642be5e438869248fa98ee9
    networks:
      - HexagonalArchitectureTemplateDocker_network
    ports:
      - "4242:4242"
    environment:
      # This points Unleash to its backing database
      DATABASE_URL: "postgres://postgres:postgres@postgres_db:5432/demo_db"
      # Disable SSL for database connections.
      DATABASE_SSL: "false"
      # Changing log levels:
      LOG_LEVEL: "warn"
      INIT_FRONTEND_API_TOKENS: "default:development.unleash-insecure-frontend-api-token"
      # The default API token is insecure and should not be used in production.
      INIT_BACKEND_API_TOKENS: "default:development.unleash-insecure-api-token"
    depends_on:
      postgres_db:
        condition: service_healthy
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:4242/health || exit 1
      interval: 1s
      timeout: 1m
      retries: 5
      start_period: 15s

  monitoring_otel:
    container_name: monitoring_otel
    image: grafana/otel-lgtm@sha256:48b2bba124a4604992a1e549a656ff7338a2ef93dbe80c358798602c1c94afa7
    networks:
      - HexagonalArchitectureTemplateDocker_network
    restart: always
    profiles:
      - monitoring
    ports:
      - "4317:4317" # OTLP gRPC receiver
      - "4318:4318" # OTLP HTTP receiver
      - "4000:3000" # Grafana UI

volumes:
  postgres-data:
